// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLatitudeChange();
void onLongitudeChange();
void onDayChange();
void onForecastScheduleChange();

float latitude;
float longitude;
int day;
CloudLocation weatherLocation;
CloudSchedule forecastSchedule;

void initProperties(){

  ArduinoCloud.addProperty(latitude, READWRITE, ON_CHANGE, onLatitudeChange);
  ArduinoCloud.addProperty(longitude, READWRITE, ON_CHANGE, onLongitudeChange);
  ArduinoCloud.addProperty(day, READWRITE, ON_CHANGE, onDayChange);
  ArduinoCloud.addProperty(weatherLocation, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(forecastSchedule, READWRITE, ON_CHANGE, onForecastScheduleChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

