// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


float humi;
float tempC;
float tempF;
int hours;
int minutes;

void initProperties(){

  ArduinoCloud.addProperty(humi, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempF, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(hours, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(minutes, READ, ON_CHANGE, NULL);


  ArduinoCloud.updateCertificate(CERT_AUTHORITY, CERT_SERIAL, CERT_NOT_BEFORE, CERT_NOT_AFTER, CERT_SIGNATURE_RS);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

